// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Token string `json:"token"`
}

type LoginRes struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type GetUniqueProfileRes struct {
	Id       string `json:"id"`
	UserId   string `json:"userId"`
	Name     string `json:"name"`
	ImageUrl string `json:"imageUrl"`
	Email    string `json:"email"`
}

type PatchProfileReq struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	ImageUrl string `json:"imageUrl"`
	Email    string `json:"email"`
}

type DeleteProfileReq struct {
	Id string `json:"id"`
}

type GetServersReq struct {
	Id         string `form:"id,optional"`
	ProfileId  string `form:"profileId,optional"`
	Name       string `form:"name,optional"`
	InviteCode string `form:"inviteCode,optional"`
	Page       int    `form:"page,optional"`
	PagePerNum int    `form:"pagePerNum,optional"`
}

type GetServerReq struct {
	ServerId string `path:"serverId"`
}

type ServerMember struct {
	Id        string `json:"id"`
	Role      string `json:"role"`
	ProfileId string `json:"profileId"`
	Name      string `json:"name"`
	ImageUrl  string `json:"imageUrl"`
	Email     string `json:"email"`
}

type ServerChannel struct {
	Id       string `json:"id"`
	Type     string `json:"type"`
	ServerId string `json:"serverId"`
	Name     string `json:"name"`
}

type GetServerRes struct {
	Id         string          `json:"id"`
	Name       string          `json:"name"`
	ImageUrl   string          `json:"imageUrl"`
	InviteCode string          `json:"inviteCode"`
	ProfileId  string          `json:"profileId"`
	Members    []ServerMember  `json:"members"`
	Channels   []ServerChannel `json:"channels"`
}

type PostServerReq struct {
	Name     string `json:"name"`
	ImageUrl string `json:"imageUrl"`
}

type PatchServerReq struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	ImageUrl   string `json:"imageUrl"`
	InviteCode string `json:"inviteCode"`
	ProfileId  string `json:"profileId"`
}

type DeleteServerReq struct {
	Id string `json:"id"`
}

type InviteMemberReq struct {
	InviteCode string `json:"inviteCode"`
}

type PatchMemberReq struct {
	Id        string `json:"id"`
	Role      string `json:"role"`
	ServerId  string `json:"serverId"`
	ProfileId string `json:"profileId"`
}

type DeleteMemberReq struct {
	Id       string `json:"id"`
	ServerId string `json:"serverId"`
}
