// Code generated by goctl. DO NOT EDIT.
// Source: servers.proto

package server

import (
	"context"

	"github.com/POABOB/go-discord/apps/servers/rpc/internal/logic/memberrpc"
	"github.com/POABOB/go-discord/apps/servers/rpc/internal/svc"
	"github.com/POABOB/go-discord/apps/servers/rpc/pb/rpc"
)

type MemberRpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedMemberRpcServer
}

func NewMemberRpcServer(svcCtx *svc.ServiceContext) *MemberRpcServer {
	return &MemberRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberRpcServer) InviteMember(ctx context.Context, in *rpc.InviteMemberReq) (*rpc.GetServerRes, error) {
	l := memberrpclogic.NewInviteMemberLogic(ctx, s.svcCtx)
	return l.InviteMember(in)
}

func (s *MemberRpcServer) PatchMember(ctx context.Context, in *rpc.PatchMemberReq) (*rpc.GetServerRes, error) {
	l := memberrpclogic.NewPatchMemberLogic(ctx, s.svcCtx)
	return l.PatchMember(in)
}

func (s *MemberRpcServer) DeleteMember(ctx context.Context, in *rpc.DeleteMemberReq) (*rpc.GetServerRes, error) {
	l := memberrpclogic.NewDeleteMemberLogic(ctx, s.svcCtx)
	return l.DeleteMember(in)
}
