// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: apps/profile/rpc/profile.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Rpc_GetUniqueProfileOrCreate_FullMethodName = "/profileRPC.Rpc/GetUniqueProfileOrCreate"
	Rpc_PatchProfile_FullMethodName             = "/profileRPC.Rpc/PatchProfile"
	Rpc_DeleteProfile_FullMethodName            = "/profileRPC.Rpc/DeleteProfile"
)

// RpcClient is the client API for Rpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcClient interface {
	GetUniqueProfileOrCreate(ctx context.Context, in *GetUniqueProfileOrCreateReq, opts ...grpc.CallOption) (*GetUniqueProfileOrCreateRes, error)
	PatchProfile(ctx context.Context, in *PatchProfileReq, opts ...grpc.CallOption) (*EmptyRes, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileReq, opts ...grpc.CallOption) (*EmptyRes, error)
}

type rpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcClient(cc grpc.ClientConnInterface) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) GetUniqueProfileOrCreate(ctx context.Context, in *GetUniqueProfileOrCreateReq, opts ...grpc.CallOption) (*GetUniqueProfileOrCreateRes, error) {
	out := new(GetUniqueProfileOrCreateRes)
	err := c.cc.Invoke(ctx, Rpc_GetUniqueProfileOrCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) PatchProfile(ctx context.Context, in *PatchProfileReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, Rpc_PatchProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) DeleteProfile(ctx context.Context, in *DeleteProfileReq, opts ...grpc.CallOption) (*EmptyRes, error) {
	out := new(EmptyRes)
	err := c.cc.Invoke(ctx, Rpc_DeleteProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServer is the server API for Rpc service.
// All implementations must embed UnimplementedRpcServer
// for forward compatibility
type RpcServer interface {
	GetUniqueProfileOrCreate(context.Context, *GetUniqueProfileOrCreateReq) (*GetUniqueProfileOrCreateRes, error)
	PatchProfile(context.Context, *PatchProfileReq) (*EmptyRes, error)
	DeleteProfile(context.Context, *DeleteProfileReq) (*EmptyRes, error)
	mustEmbedUnimplementedRpcServer()
}

// UnimplementedRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRpcServer struct {
}

func (UnimplementedRpcServer) GetUniqueProfileOrCreate(context.Context, *GetUniqueProfileOrCreateReq) (*GetUniqueProfileOrCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUniqueProfileOrCreate not implemented")
}
func (UnimplementedRpcServer) PatchProfile(context.Context, *PatchProfileReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchProfile not implemented")
}
func (UnimplementedRpcServer) DeleteProfile(context.Context, *DeleteProfileReq) (*EmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedRpcServer) mustEmbedUnimplementedRpcServer() {}

// UnsafeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServer will
// result in compilation errors.
type UnsafeRpcServer interface {
	mustEmbedUnimplementedRpcServer()
}

func RegisterRpcServer(s grpc.ServiceRegistrar, srv RpcServer) {
	s.RegisterService(&Rpc_ServiceDesc, srv)
}

func _Rpc_GetUniqueProfileOrCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniqueProfileOrCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetUniqueProfileOrCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_GetUniqueProfileOrCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetUniqueProfileOrCreate(ctx, req.(*GetUniqueProfileOrCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_PatchProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).PatchProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_PatchProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).PatchProfile(ctx, req.(*PatchProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rpc_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).DeleteProfile(ctx, req.(*DeleteProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rpc_ServiceDesc is the grpc.ServiceDesc for Rpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profileRPC.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUniqueProfileOrCreate",
			Handler:    _Rpc_GetUniqueProfileOrCreate_Handler,
		},
		{
			MethodName: "PatchProfile",
			Handler:    _Rpc_PatchProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _Rpc_DeleteProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/profile/rpc/profile.proto",
}
